### ISSUE TITLE
Sheet Options Icon Button Color Mode

### ISSUE THREAD

**Issue by TClark1011** [TClark1011/bag-of-holding#1]
The sheet options icon button's backdrop is always dark regardless of the active color mode, causing it to have a grey overlay when hovered in light mode.

![image](https://user-images.githubusercontent.com/48699309/113652033-69f89a80-96d6-11eb-9493-19ffbdbdc4be.png)

It should be wrapped in the 'DarkMode' component from Chakra UI which will ensure it always uses dark mode colors.

The code is located in `/pages/sheets/[sheetid].tsx`

![image](https://user-images.githubusercontent.com/48699309/113652551-50a41e00-96d7-11eb-81f8-2903d1620da7.png)

**Comment by punkadeedle** [comment]
Can you assign this issue to me, please?
