### ISSUE TITLE
Use 'big.js' for calculating values that are shown in sheets

### ISSUE THREAD

**Issue by TClark1011** [TClark1011/bag-of-holding#59]
Currently, the total weight and value values that are derived by multiplying an item's weight/value attributes by it's quantity can sometimes be calculated incorrectly:
![image](https://user-images.githubusercontent.com/48699309/117219776-4fd2e900-ae49-11eb-975e-2c187cd75b86.png)
(expected weight in this situation would be `1.5`)

Implement math with [big.js](https://github.com/MikeMcl/big.js/) for calculating display values. eg; weight and value of items when multiplied by the quantity.

The code for these calculations are in the `InventorySheetTable.tsx` file:
![image](https://user-images.githubusercontent.com/48699309/117219098-e69ea600-ae47-11eb-9054-cf2669ebf13d.png)
As well as `MemberCarryWeightTable.tsx`:
![image](https://user-images.githubusercontent.com/48699309/117219159-08982880-ae48-11eb-8952-beeaed92bfa2.png)

When doing this, you should also refactor the `weight * quantity` and `value * quantity` calculations into external `getItemTotalWeight` and `getItemTotalValue` functions respectively, with both functions taking the item as their only parameter. These functions should be written in a file named `deriveItemProperties.ts` inside the `utils` folder.

**Comment by punkadeedle** [comment]
Can you assign this issue to me, please?
