### ISSUE TITLE
Rename `MemberCarryWeightTable` to `MemberTotalsTable`

### ISSUE THREAD

**Issue by TClark1011** [TClark1011/bag-of-holding#84]
Rename the `MemberCarryWeightTable` component and the file it is contained in to `MemberTotalsTable`. Fix all imports of the component to use the name `MemberTotalsTable`.

This change should help make the purpose of the component more clear.

**Comment by punkadeedle** [comment]
Can you assign this issue to me, please?

**Comment by TClark1011** [comment]
assigned
